# --------------------------------------------
#
# Standard recommended semantic-release configuration.
#
# Alternative configurations
#  - A .releaserc file, written in YAML or JSON, with optional extensions: .yaml/.yml/.json/.js
#  - A release.config.js file that exports an object
#  - A release key in the project's package.json file
#  Source: https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file
#
#----------------------------------------------

---
branches:
  - master
  - main
plugins:
  - "@semantic-release-cargo/semantic-release-cargo"
  - assets:
      - CHANGELOG.md
      - dist/global_retention_setter/bootstrap
      - dist/log_retention_setter/bootstrap
      - README.md
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
